### ISSUE TITLE
entities#show (ActionController::UrlGenerationError) "No route matches {:action=>\"list_supplier_journal_ent...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1753] opened 2017-03-28 07:22 UTC
## Error
An ActionController::UrlGenerationError occurred in entities#show:

  No route matches {:action=>"list_supplier_journal_entry_items", :controller=>"backend/entities", :dir=>"", :format=>"xcsv", :id=>"759", :redirect=>"/backend/entities/759", :sort=>""}
  app/helpers/application_helper.rb:215:in `link_to'

---
## Environment
- **Version :** 2.38.0
- **Server :** preprod
- **Date :** 28/03/2017

**Comment by Aquaj** [comment] 2017-03-28 08:51
Fixed by a181ea5acf9f.

**Comment by Aquaj** [comment] 2017-03-28 08:52
Had wrongly closed. The issue is still relevant.

**Closed** 2017-03-28 10:12 UTC
Labels: Bug, Preprod
