### ISSUE TITLE
Issue #788 not completely resolved for the VAT problem

### ISSUE THREAD

**Issue by bainacitron** [ekylibre/ekylibre#796] opened 2016-07-09 08:30 UTC
Hello, 

I created an issue regarding a bug in the accounting section of your service.
This issue was including several problems and only one have been resolved.

The VAT field not showing the rates is still not working.
When I enter some purchases for my company or try to log a sale, the interface does not allow me to select the VAT rate anymore. I've been using your solution for several months and this was working well. Since about 1,5 months it doesn't anymore.
The VAT field is shown when creating the invoice, but when I click on it, it does not show any menu to select the VAT rate to apply, while all my VAT rates are well configured in the "configuration" section and my product price catalogue is filled as well.

This is a blocking issue. Thank you for your support.
![vat issue](https://cloud.githubusercontent.com/assets/20242636/16706947/db043300-45bf-11e6-84f2-03fb1dd6aae2.png)

**Comment by PH64** [comment] 2016-07-09 09:47
Can't reproduce this issue. Seems to be a bad configuration. Click on "Load" in taxes configuration, this should solve the problem.

Note, support isn't assured here. For any problems contact the Support Ekylibre. Thanks

**Comment by bainacitron** [comment] 2016-07-09 13:10
Thank you for the feedback the the « Load » function in the Taxes section does not work either. 


It goes to a page saying :


Nous sommes désolés, mais quelque chose s'est mal passé


L'application rencontre des problèmes. Les administrateurs ont été notifiés.

I tried several times and it always goes to this page.

**Comment by burisu** [comment] 2016-07-20 21:04
Fixed by @Aquaj in cb1e79354d2c17dc824b45893b9faac339eaf471

**Closed by burisu** 2016-07-20 21:04 UTC
Labels: Accountancy, Bug, Question
