### ISSUE TITLE
PG::InternalError: Relate Operation called with a LWGEOMCOLLECTION type in crumbs#index

### ISSUE THREAD

**Issue by Coren** [ekylibre/ekylibre#293] opened 2014-11-16 13:17 UTC
An ActionView::Template::Error occurred in crumbs#index:

  PG::InternalError: ERROR:  Relate Operation called with a LWGEOMCOLLECTION type.  This is unsupported.
HINT:  Change argument 1: 'GEOMETRYCOLLECTION(POLYGON((-0.7864068748313 45.8269152924779,-0.786315679724...'
: SELECT DISTINCT "products".* FROM "products" INNER JOIN "product_readings" ON "product_readings"."product_id" = "products"."id" INNER JOIN crumbs ON (indicator_datatype = 'geometry' AND ST_CONTAINS(product_readings.geometry_value, crumbs.geolocation)) WHERE (crumbs.id IN (58,57,56,55,54,53,52,51,50,49,48,47,46,45,44,43,42,41,40,39,38,37,36,35,34,33,32,31,30,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,200,199,198,197,196,195,194,193,192,191,190,189,188,187,186,185,184,183,182,181,180,179,178,177,176,175,174,173,172,171,170,169,168,167,166,165,164,163,162,161,160,159,158,157,156,155,154,153,152,151,150,149,148,147,146,145,144,143,142,141,140,139,138,137,136,135,134,133,132,131,130,129,128,127,126,125,124,123,122,121,120,119,118,117,116,115,114,113,112,111,110,109,108,107,106,105,104,103,102,101,100,99,98,97,96,95,94,93,92,91,90,89,88,87,86,85,84,83,82,81,80,79,78,77,76,75,74,73,72,71,70,69,68,67,66,65,64,63,62,61,60,59))
  app/models/crumb.rb:117:in `products'

Request:

  * URL        : https://www.ekylibre.org/backend/crumbs

**Comment by burisu** [comment] 2015-01-05 15:41
I can't reproduce the bug, so I close it for now.

**Comment by burisu** [comment] 2015-03-10 10:48
Again:

An ActionView::Template::Error occurred in crumbs#index:

  PG::InternalError: ERROR:  Relate Operation called with a LWGEOMCOLLECTION type.  This is unsupported.
HINT:  Change argument 1: 'GEOMETRYCOLLECTION(POLYGON((-0.819624066352844 45.8237752183752,-0.7921582460...'
: SELECT DISTINCT "products".* FROM "products" INNER JOIN "product_readings" ON "product_readings"."product_id" = "products"."id" INNER JOIN crumbs ON (indicator_datatype = 'geometry' AND ST_CONTAINS(product_readings.geometry_value, crumbs.geolocation)) WHERE (crumbs.id IN (200,199,198,197,196,195,194,193,192,191,190,189,188,187,186,185,184,183,182,181,180,179,178,177,176,175,174,173,172,171,170,169,168,167,166,165,164,163,162,161,160,159,158,157,156,155,154,153,152,151,150,149,148,147,146,145,144,143,142,141,140,139,138,137,136,135,134,133,132,131,130,129,128,127,126,125,124,123,122,121,120,119,118,117,116,115,114,113,112,111,110,109,108,107,106,105,104,103,102,101,100,99,98,97,96,95,94,93,92,91,90,89,88,87,86,85,84,83,82,81,80,79,78,77,76,75,74,73,72,71,70,69,68,67,66,65,64,63,62,61,60,59))
  app/models/crumb.rb:116:in `products'


-------------------------------
Request:
-------------------------------

  * URL        : http://demo.ekylibre.farm/backend/crumbs
  * HTTP Method: GET
  * Parameters : {"controller"=>"backend/crumbs", "action"=>"index"}
  * Timestamp  : 2015-03-10 08:56:26 +0100
  * Server : ma001
  * Rails root : /var/www/sheep-demo/releases/20150308192415-ekylibre-1.1.0.rc1
  * Process: 6902

-------------------------------
Environment:
-------------------------------

  * HTTP_ACCEPT                                    : text/html, application/xhtml+xml, application/xml
  * HTTP_ACCEPT_CHARSET                            : utf-8, utf-16, *;q=0.7
  * HTTP_ACCEPT_ENCODING                           : gzip,deflate
  * HTTP_ACCEPT_LANGUAGE                           : fr-FR, en-US
  * HTTP_CONNECTION                                : close
  * HTTP_HOST                                      : demo.ekylibre.farm
  * HTTP_REFERER                                   : https://demo.ekylibre.farm/backend/dashboards/production
  * HTTP_USER_AGENT                                : Mozilla/5.0 (Linux; U; Android 4.2.2; fr-fr; thl T100S Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
  * HTTP_VERSION                                   : HTTP/1.0
  * HTTP_X_FORWARDED_FOR                           : 37.165.57.200
  * HTTP_X_REAL_IP                                 : 37.165.57.200
  * HTTP_X_REQUESTED_WITH                          : com.android.browser
  * HTTP_X_WAP_PROFILE                             : http://218.249.47.94/Xianghe/MTK_Phone_JB_UAprofile.xml
  * HTTP_X_XHR_REFERER                             : https://demo.ekylibre.farm/backend/dashboards/production
  * ORIGINAL_FULLPATH                              : /backend/crumbs
  * ORIGINAL_SCRIPT_NAME                           : 
  * PATH_INFO                                      : /backend/crumbs
  * QUERY_STRING                                   : 
  * REMOTE_ADDR                                    : 127.0.0.1
  * REQUEST_METHOD                                 : GET
  * REQUEST_PATH                                   : /backend/crumbs
  * REQUEST_URI                                    : /backend/crumbs
  * ROUTES_70018421611580_SCRIPT_NAME              : 
  * SCRIPT_NAME                                    : 
  * SERVER_NAME                                    : demo.ekylibre.farm
  * SERVER_PORT                                    : 80
  * SERVER_PROTOCOL                                : HTTP/1.0
  * SERVER_SOFTWARE                                : Unicorn 4.8.3
  * action_controller.instance                     : #<Backend::CrumbsController:0x007f5ce16d02c8>
  * action_dispatch.backtrace_cleaner              : #<Rails::BacktraceCleaner:0x007f5ce50953c8>
  * action_dispatch.cookies                        : #<ActionDispatch::Cookies::CookieJar:0x007f5ce16ea128>
  * action_dispatch.cookies_digest                 : 
  * action_dispatch.cookies_serializer             : json
  * action_dispatch.encrypted_cookie_salt          : encrypted cookie
  * action_dispatch.encrypted_signed_cookie_salt   : signed encrypted cookie
  * action_dispatch.http_auth_salt                 : http authentication
  * action_dispatch.key_generator                  : #<ActiveSupport::CachingKeyGenerator:0x007f5ce59eb260>

-------------------------------
Backtrace:
-------------------------------

  app/models/crumb.rb:116:in `products'
  app/models/crumb.rb:131:in `production_supports'
  app/views/backend/crumbs/index.html.haml:31:in `_app_views_backend_crumbs_index_html_haml__4404175644568065645_70018451961660'

**Comment by burisu** [comment] 2015-03-26 11:10
We need to use http://postgis.net/docs/ST_CollectionExtract.html

**Closed** 2015-03-26 11:14 UTC
Labels: Bug, Production
