### ISSUE TITLE
sales#create "Attempted to update a stale object: Sequence"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1139] opened 2016-09-30 08:55 UTC
An ActiveRecord::StaleObjectError occurred in sales#create:

  Attempted to update a stale object: Sequence
  app/models/sequence.rb:146:in `next_value!'

**Comment by Aquaj** [comment] 2017-03-09 17:28
Duplicate of #1417 .

**Closed by Aquaj** 2017-03-09 17:28 UTC
Labels: Bug, Prod
