### ISSUE TITLE
interventions#compute "757: unexpected token at 'SRID=4326;MULTIPOLYGON EMPTY'"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1177] opened 2016-10-10 06:45 UTC
A JSON::ParserError occurred in interventions#compute:

  757: unexpected token at 'SRID=4326;MULTIPOLYGON EMPTY'
  lib/charta/geo_json.rb:8:in `initialize'

**Comment by Aquaj** [comment] 2017-03-17 16:10
Duplicate of #1219 .

**Closed by Aquaj** 2017-03-17 16:10 UTC
Labels: Bug, Prod
