### ISSUE TITLE
public#index "Attempted to update a stale object: User"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1190] opened 2016-10-11 11:51 UTC
An ActiveRecord::StaleObjectError occurred in public#index:

  Attempted to update a stale object: User
  lib/userstamp/controller.rb:27:in `set_stamper'

**Comment by Aquaj** [comment] 2017-03-09 17:32
Duplicate of #1631.

**Closed by Aquaj** 2017-03-09 17:32 UTC
Labels: Bug, Prod
