### ISSUE TITLE
Equipment: "undefined container" in Inventory

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#746] opened 2016-06-15 09:52 UTC
Inventory do not record equipment containers:

In **stock/inventory/new inventory**:

![container01](https://cloud.githubusercontent.com/assets/17082331/16075535/9f227fb4-32ef-11e6-97d6-4dac246e0b6f.PNG)

Unless it is well defined in equipment...
In **Setting/Equipment**:

![container02](https://cloud.githubusercontent.com/assets/17082331/16075539/a1445772-32ef-11e6-813b-3148162543bc.PNG)

**Comment by PH64** [comment] 2016-06-15 14:40
Are you sure Parking 01 have ability to stock equipment ?

**Comment by Nicephore17** [comment] 2016-06-15 14:55
Parking 01 was a (generic) **Building division**. I changed it to be a **Equipment Building Divison** with **Store equipment** hability: same problem.

As well, container is not showed in **Settings/Equipment**.
![container03](https://cloud.githubusercontent.com/assets/17082331/16084673/ea49f7e0-3319-11e6-9e35-65ff3ffa285a.PNG)

**Comment by PH64** [comment] 2016-06-15 15:05
Is MQE the same entities as the farm use in Ekylibre ?

**Comment by Nicephore17** [comment] 2016-06-15 15:27
Connexion bug ?

**Comment by PH64** [comment] 2016-06-15 15:31
I don't think it's a bug, probably a setup problem

**Comment by Nicephore17** [comment] 2016-06-16 06:21
So, what variant should I use ?

**Comment by PH64** [comment] 2016-06-16 12:47
If you create a building division with "Zone de stockage des aliments et du matériel", it should work.

**Comment by Nicephore17** [comment] 2016-06-16 12:55
**Food equipment division** ?

**Comment by Nicephore17** [comment] 2016-06-16 13:00
Same problem with "Parking 2" which is a Food equipment division.
I have may stock problem: urea is not listed it its container unless the owner and the container are clearly defined...

**Comment by PH64** [comment] 2016-06-16 13:05
Could you mail me screenshot of your building division because I don't reproduce this issue.

**Comment by Nicephore17** [comment] 2016-06-16 13:08
Translation issue by the way --> https://github.com/ekylibre/ekylibre/issues/747

**Last one:**
![eqdivision](https://cloud.githubusercontent.com/assets/17082331/16117791/21520f88-33d4-11e6-9c71-3106fb8fe0ac.PNG)

**Comment by PH64** [comment] 2016-06-16 13:16
I don't reproduce the problem in the instance "demo" with a building division "parking". Could you see what is different in your instance

**Comment by Nicephore17** [comment] 2016-06-16 13:37
I have no idea, I cannot link matter or equipment to storage area unless all seem to be well defined...? Should I give you access to Liwa instance ?

**Comment by PH64** [comment] 2016-06-16 13:39
Yes, if you want

**Comment by Nicephore17** [comment] 2016-06-16 13:43
I sent you an invitation from the instance.

**Comment by PH64** [comment] 2016-06-16 13:44
thanks

**Comment by PH64** [comment] 2016-06-16 14:08
When I update your equipment, it's appear in the inventories. I suppose it's related to abilities change of yhe building division.
But, there's always the bug on modification of the equipment when they are used

**Comment by Nicephore17** [comment] 2016-06-16 14:17
OK.
Did you see I have the same problem with my stock of Urea and I cannot change its container...
We keep the issue open until it's solved ?

**Comment by PH64** [comment] 2016-06-16 14:20
@EmmaDorie will close this issue to create a new issue on different problem in Building division / Installation / equipment modification

**Comment by Nicephore17** [comment] 2016-06-16 14:21
OK. I'll try to fix my equipment an we will see for the matters.

**Comment by PH64** [comment] 2016-06-16 14:26
There is a bug on the matter : to have matter in a container, the "initial owner" must be the farm and not the the supplier
It would be change with new delivery procedure

**Comment by Nicephore17** [comment] 2016-06-16 14:28
The matter I use was added by **Stock / Matters / Add** instead of delivery.
I think I sat the good ownership but I can't check now as it the owner is not available in edition.

**Comment by PH64** [comment] 2016-06-16 14:30
Yes, it's the same bug as equipment modification.
Could you test with an other product

**Closed** 2016-06-16 19:21 UTC
