### ISSUE TITLE
interventions#create (ActiveRecord::StaleObjectError) "Attempted to update a stale object: Sequence"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1296] opened 2016-11-02 08:11 UTC
An ActiveRecord::StaleObjectError occurred in interventions#create:

  Attempted to update a stale object: Sequence
  app/models/sequence.rb:146:in `next_value!'

**Comment by Aquaj** [comment] 2017-01-02 15:42
Closed as duplicate of #1346.

**Closed by Aquaj** 2017-01-02 15:42 UTC
Labels: Bug, Prod
