### ISSUE TITLE
matters#new (ActionView::Template::Error) "Association :fixed_asset not found"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1758] opened 2017-03-31 14:50 UTC
## Error
An ActionView::Template::Error occurred in matters#new:

  Association :fixed_asset not found
  app/helpers/backend/form_builder.rb:721:in `referenced_association_input_options'

---
## Environment
- **Version :** 2.39.1
- **Server :** production
- **Date :** 31/03/2017

**Comment by Aquaj** [comment] 2017-03-31 14:51
Duplicate of #1756. Fixed by 74fbdc7.

**Closed by Aquaj** 2017-03-31 14:51 UTC
Labels: Bug, Prod
