### ISSUE TITLE
sales#invoice (ActiveRecord::StaleObjectError) "Attempted to update a stale object: Sequence"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1477] opened 2016-12-14 08:15 UTC
## Error
An ActiveRecord::StaleObjectError occurred in sales#invoice:

  Attempted to update a stale object: Sequence
  app/models/sequence.rb:146:in `next_value!'

---
## Environment
- **Version :** 2.25.1
- **Server :** production

**Comment by Aquaj** [comment] 2017-03-09 17:32
Duplicate of #1346.

**Closed by Aquaj** 2017-03-09 17:32 UTC
Labels: Bug, Prod
