### ISSUE TITLE
products#create ProductNatureVariant(#70065306835240) expected, got String(#70065208313720)

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1203] opened 2016-10-13 13:06 UTC
An ActiveRecord::AssociationTypeMismatch occurred in products#create:

  ProductNatureVariant(#70065306835240) expected, got String(#70065208313720)
  app/models/product.rb:334:in `new_with_cast'
- Parameters : {"product"=>{"variant"=>"285"}, "dialog"=>"dialog-0", "controller"=>"backend/products", "action"=>"create"}

**Comment by Aquaj** [comment] 2016-11-03 16:14
Removed label Frequent as the bug only happened 8 times since June.

**Comment by Aquaj** [comment] 2016-11-03 16:15
Also, closing as it is a duplicate of #1125.

**Closed by Aquaj** 2016-11-03 16:15 UTC
Labels: Bug, Prod
