### ISSUE TITLE
interventions#create (ActiveRecord::StaleObjectError) "Attempted to update a stale object: Sequence"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1346] opened 2016-11-16 15:03 UTC
## Error
An ActiveRecord::StaleObjectError occurred in interventions#create:

  Attempted to update a stale object: Sequence
  app/models/sequence.rb:146:in `next_value!'

--
## Environnment :
- **Version :** 2.19.0
- **Server :** Prod
- **Instance Keyfield** 

--
## Request:
- **Parameters :** {"format"=>"xml", "controller"=>"keyfield/v1/interventions", "action"=>"create"}

**Comment by Aquaj** [comment] 2017-01-02 15:42
Duplicate of #1296: keeping this one as it has more details.

**Closed** 2017-09-19 14:13 UTC
Labels: Bug, Prod
