### ISSUE TITLE
attachments#create (ActiveRecord::StaleObjectError) "Attempted to update a stale object: Sequence"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1417] opened 2016-12-01 07:37 UTC
## Error
An ActiveRecord::StaleObjectError occurred in attachments#create:

  Attempted to update a stale object: Sequence
  app/models/sequence.rb:146:in `next_value!'

---
## Environment
- **Version :** 2.21.5
- **Server :** production

**Comment by Aquaj** [comment] 2017-03-09 17:29
Duplicate of #1296.

**Closed by Aquaj** 2017-03-09 17:29 UTC
Labels: Bug, Prod
