### ISSUE TITLE
interventions#create (ActiveRecord::StaleObjectError) "Attempted to update a stale object: Sequence"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1692] opened 2017-02-27 08:38 UTC
## Error
An ActiveRecord::StaleObjectError occurred in interventions#create:

  Attempted to update a stale object: Sequence
  app/models/sequence.rb:146:in `next_value!'

---
## Environment
- **Version :** 2.35.0
- **Server :** production

**Comment by Aquaj** [comment] 2017-03-09 17:30
Duplicate of #1569.

**Closed by Aquaj** 2017-03-09 17:30 UTC
Labels: Bug, Prod
