### ISSUE TITLE
List of interventions doesn't appear in backend/activity_productions#show view

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#528] opened 2016-03-31 08:22 UTC
The list of interventions link to one production doesn't appear in the production view.
![interventions_list](https://cloud.githubusercontent.com/assets/11627573/14169823/4bb40efc-f72a-11e5-81b7-2f885a78c6e0.jpg)

**Comment by ionosphere** [comment] 2016-05-02 12:06
The problem seems to be link with heritage in Rails.

For example, the scope :of_generic_role in InterventionParameter

```ruby
scope :of_generic_role, lambda { |role|
    role = role.to_s
    unless %w(doer input output target tool).include?(role)
      raise ArgumentError, "Invalid role: #{role}"
    end
    where(type: "Intervention#{role.camelize}")
  }
```
produce

```sql
SELECT  "interventions".* FROM "interventions" 
WHERE "interventions"."id" 
IN (SELECT "intervention_parameters"."intervention_id" FROM "intervention_parameters" 
WHERE "intervention_parameters"."type" 
IN ('InterventionProductParameter') AND "intervention_parameters"."type" = 'InterventionOutput' AND "intervention_parameters"."product_id" = 586)  
ORDER BY "interventions"."id"
ASC LIMIT 1
```

the problem is link to  WHERE "intervention_parameters"."type" 
IN ('InterventionProductParameter') because all the childs are missing.

**Comment by burisu** [comment] 2016-05-03 18:56
From what line did you call `of_generic_role` scope?

After some tests, I can't reproduce your SQL query:
```
pry(main)> InterventionProductParameter.of_generic_role(:target)
  InterventionProductParameter Load (0.4ms)  SELECT "intervention_parameters".* FROM "intervention_parameters" WHERE "intervention_parameters"."type" IN ('InterventionProductParameter', 'InterventionTarget', 'InterventionAgent', 'InterventionDoer', 'InterventionTool') AND "intervention_parameters"."type" = $1  [["type", "InterventionTarget"]]
```
Or:
```
 pry(main)> i = Intervention.first
 pry(main)> i.product_parameters
  InterventionProductParameter Load (0.6ms)  SELECT "intervention_parameters".* FROM "intervention_parameters" WHERE "intervention_parameters"."type" IN ('InterventionProductParameter', 'InterventionTarget', 'InterventionAgent', 'InterventionDoer', 'InterventionTool') AND "intervention_parameters"."intervention_id" = 9
```
Or:
```
[8] pry(main)> Intervention.with_generic_cast(:target, Plant.first)
  Plant Load (0.8ms)  SELECT  "products".* FROM "products" WHERE "products"."type" IN ('Plant')  ORDER BY "products"."id" ASC LIMIT 1
  Intervention Load (0.5ms)  SELECT "interventions".* FROM "interventions" WHERE "interventions"."id" IN (SELECT "intervention_parameters"."intervention_id" FROM "intervention_parameters" WHERE "intervention_parameters"."type" IN ('InterventionProductParameter', 'InterventionTarget', 'InterventionAgent', 'InterventionDoer', 'InterventionTool') AND "intervention_parameters"."type" = $1 AND "intervention_parameters"."product_id" = $2)  [["type", "InterventionTarget"], ["product_id", 90]]
```

**Comment by ionosphere** [comment] 2016-05-03 19:12
The last one.
in my case, i haven't got exactly the same thing near WHERE "intervention_parameters"."type" IN ('InterventionProductParameter')
```batch
[7] pry(main)> i = Intervention.with_generic_cast(:output, p)
  Intervention Load (0.4ms)  SELECT "interventions".* FROM "interventions" WHERE "interventions"."id" IN (SELECT "intervention_parameters"."intervention_id" FROM "intervention_parameters" WHERE "intervention_parameters"."type" IN ('InterventionProductParameter') AND "intervention_parameters"."type" = $1 AND "intervention_parameters"."product_id" = $2)  [["type", "InterventionOutput"], ["product_id", 537]]
=> []
```

**Comment by burisu** [comment] 2016-05-04 06:03
On my side, I got that:
```
[10] pry(main)> i = Intervention.with_generic_cast(:target, Plant.first)
  Plant Load (0.5ms)  SELECT  "products".* FROM "products" WHERE "products"."type" IN ('Plant')  ORDER BY "products"."id" ASC LIMIT 1
  Intervention Load (0.4ms)  SELECT "interventions".* FROM "interventions" WHERE "interventions"."id" IN (SELECT "intervention_parameters"."intervention_id" FROM "intervention_parameters" WHERE "intervention_parameters"."type" IN ('InterventionProductParameter', 'InterventionOutput', 'InterventionInput') AND "intervention_parameters"."type" = $1 AND "intervention_parameters"."product_id" = $2)  [["type", "InterventionTarget"], ["product_id", 90]]
```

**Comment by burisu** [comment] 2016-05-04 06:07
Maybe you have a example in the app, in the terminal if you load wanted models you'll have what you want.

**Comment by Nyxelio** [comment] 2016-06-03 09:20
I agree it works if models are loaded.

**Comment by EmmaDorie** [comment] 2016-06-06 12:54
The issue still exists in v 2.0.0. rc23

**Comment by Nicephore17** [comment] 2016-06-16 08:43
The issue still exists in v.2.0.0rc24.

**Comment by Nyxelio** [comment] 2016-06-23 16:15
It occurs when you start the server and you call a product show page. The associated interventions don't appear because of malformed sql. This is due to STI of InterventionProductParameter model. To manually force inheritance, you need to go to the interventions page and come back to product show page.

**Comment by Nyxelio** [comment] 2016-06-24 07:58
Fixed by 1abdaf0085f8da4ea60e2a7b97ee61864104ac94 and b2ec808fdd432f5c4d73573dcf6f7e3c14e94220

**Comment by Nicephore17** [comment] 2016-07-04 06:18
Sorry but it is not working with v2.0.0rc24 on SaaS.
Same problem on demo.

:(

@burisu @Nyxelio @ionosphere

**Comment by Nicephore17** [comment] 2016-07-04 06:22
I'm investigation. It look of on some production: https://demo.ekylibre.farm/backend/activity_productions/51

**Comment by Nicephore17** [comment] 2016-07-04 06:23
Does it take only intervention made in 2016 as there is no year selector ??

**Comment by Nicephore17** [comment] 2016-07-04 06:27
I try to create 2 interventions today (to be in 2016 then) one targeting the crop and the other targeting the parcel. None of them show up in Intervention list.

**Comment by burisu** [comment] 2016-07-04 06:29
No filters on campaign (https://github.com/ekylibre/ekylibre/blob/2.0.0.rc25/app/controllers/backend/activity_productions_controller.rb#L34).
You need to distribute your intervention targets on yours activity_productions. See "Distribute" button on https://demo.ekylibre.farm/backend/campaigns/current or directly on https://demo.ekylibre.farm/backend/target_distributions/distribute

**Comment by Nicephore17** [comment] 2016-07-04 06:45
OK. Working then. Can you explain what it is not automatic ?

May I warn you: with many intervention, it is hard to read. Will probably be better with the _jalons_ or with consolidating intervention by type (= one graph entry for all fertilization).

![costchart](https://cloud.githubusercontent.com/assets/17082331/16552709/7c51714c-41c3-11e6-86d6-f3d57f5e9c61.PNG)

(My price a not all set so human work can seems to be really "cheap").
Intervention list so not show individual price like in **production/interventions**.

Anyway: **thank you** !

**Comment by burisu** [comment] 2016-07-04 06:52
It's not automatic for now, but it will be. As long as, interventions cannot set these distributions automatically, we'll need the user to do that distribution manually

**Comment by Nicephore17** [comment] 2016-07-04 06:53
The pre-selection look good I had just to validate it. I will check consistency but it looks fine.

**Closed** 2016-07-06 09:15 UTC
Labels: Bug, Production
