### ISSUE TITLE
Intervention kanban top bar is not correctly displayed when i scroll down the page

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1141] opened 2016-09-30 09:16 UTC
When i scroll down the page with the kanban board, i top bar with the columns name is not displayed correctly.

**Comment by igkyab** [comment] 2016-09-30 10:00
I can't reproduce ce problem on the master branch. @EmmaDorie, you reproduce it if you are on master branch ?

**Comment by EmmaDorie** [comment] 2016-10-03 09:30
I can't reproduce it again ... I close this issue for the moment.

**Closed by EmmaDorie** 2016-10-03 09:30 UTC
Labels: Bug, Production, Stalled, Test
